### ISSUE TITLE
Is it possible to add a %?

### ISSUE THREAD

**Issue by Kron98** [tinywall/numscroller#9]
Title. I am trying to show a percentage growing up, from 0% to 60% but I can't grasp my head around how to make it work :S

**Comment by reeLx** [comment]
How about adding a %-sign after the <span>-element? 

Smth. like this
`<span class='numscroller' data-min='0' data-max='60' data-delay='5' data-increment='2'>60</span>%
`

**Comment by teesvalleyarts** [comment]
@reeLx that's what we did and it worked a treat.

**Comment by Kron98** [comment]
Thank you!
